.github/workflows/pr-open.yml
---
- [Frontend](https://nr-gwells-35-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-35-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: add frontend back to GitHub build step

docker-compose.yml
---
- [Frontend](https://nr-gwells-38-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-38-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: docker compose volumes

database/Dockerfile, docker-compose.yml
---
- [Frontend](https://nr-gwells-57-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-57-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: Revert to original for db related docker compose.

renovate.json
---
- [Frontend](https://nr-gwells-61-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-61-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): renovate exclusion

.github/labeler.yaml, .github/workflows/pr-labeler.yaml
---
- [Frontend](https://nr-gwells-63-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-63-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): labeler v5 updates

backend/openshift.deploy.yml, database/postgresql.dc.yml
…oyment.
---
- [Frontend](https://nr-gwells-76-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-76-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): database deploymentConfig to deployment

common/openshift.init.yml
---
- [Frontend](https://nr-gwells-87-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-87-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Add network policies to init deployment template.

renovate.json
---
- [Frontend](https://nr-gwells-92-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-92-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Limit PRs to three.

.github/workflows/.deploy.yml, common/openshift.init.yml, minio/openshift.deploy.yml
---
- [Frontend](https://nr-gwells-111-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-111-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Testing minio secret values.

.github/workflows/.deploy.yml, backend/openshift.deploy.yml, common/openshift.init.yml
---
- [Frontend](https://nr-gwells-110-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-110-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Update database service name.

.github/workflows/.deploy.yml, .github/workflows/pr-open.yml, minio/openshift.deploy.yml
---
- [Frontend](https://nr-gwells-120-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-120-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Minio deploymentConfig to deployment.

.github/workflows/.deploy.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://nr-gwells-121-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-121-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Uncomment workflow deploy code.

.github/workflows/pr-close.yml
… to clean up.
---
- [Frontend](https://nr-gwells-132-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-132-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Update PR close workflow

.github/workflows/pr-close.yml
---
- [Frontend](https://nr-gwells-135-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-135-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Git remove init from image clean up.

.github/workflows/.deploy.yml, backend/openshift.deploy.yml, frontend/openshift.deploy.yml, minio/openshift.deploy.yml
---
- [Frontend](https://nr-gwells-151-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-151-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Remove dev prefix to simplify PR cleanup.

backend/openshift.deploy.yml, common/openshift.init.yml, database/openshift.deploy.yml, frontend/openshift.deploy.yml, minio/openshift.deploy.yml
---
- [Frontend](https://nr-gwells-152-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-152-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Update app label that clean up workflow refrences.

.github/workflows/merge.yml
---
- [Frontend](https://nr-gwells-155-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-155-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Update merge workflow to deploy to test environment.

.github/workflows/.deploy.yml, .github/workflows/merge.yml, backend/openshift.deploy.yml, common/openshift.init.yml, database/openshift.deploy.yml, frontend/openshift.deploy.yml, minio/openshift.deploy.yml
---
- [Frontend](https://nr-gwells-156-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-156-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Update name suffix

.github/workflows/.deploy.yml
---
- [Frontend](https://nr-gwells-159-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-159-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Update image tag reference.

.github/workflows/.deploy.yml
---
- [Frontend](https://nr-gwells-160-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-160-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Uncomment deploy environments.

renovate.json
---
- [Frontend](https://nr-gwells-168-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-168-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Limit renovate PRs to 1.

frontend/src/common/mapbox/popup.js, frontend/src/qaqc/components/QaQcTable.vue, frontend/src/qaqc/store/index.js, frontend/src/registry/components/people/PersonDetail.vue, frontend/src/wells/views/WellDetail.vue, frontend/src/wells/views/WellSearch.vue
Fixed 4 issues. Listed here: https://github.com/orgs/bcgov/projects/145?pane=issue&itemId=85287591&issue=bcgov%7Cnr-gwells%7C119
I did my best to test locally, but I would appreciate someone else testing the QAQC and registry sections.
---
- [Frontend](https://nr-gwells-167-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-167-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: resolve multiple console errors

docker-compose.yml
Changed Docker working_dir for the backend from /app to /backend.
---
- [Frontend](https://nr-gwells-192-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-192-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): update backend working_dir

.github/workflows/.tests.yml, .github/workflows/analysis.yml, .github/workflows/pr-open.yml
---
- [Frontend](https://nr-gwells-194-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-194-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Uncomment PR open test and results job.

.github/workflows/.deploy.yml
---
- [Frontend](https://nr-gwells-195-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-195-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Add environment to minio deploy step.

docker-compose.yml
---
- [Frontend](https://nr-gwells-203-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-203-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Update minio data directory for docker compose.

frontend/src/common/components/Header.vue, frontend/src/crosssection/views/CrossHome.vue, frontend/src/router.js, frontend/tests/unit/specs/crosssection/CrossToolHome.spec.js
Blank page created with auth (bulk) for header.
- [] test for if page renders with title
- Potential discussion on page name and proper auth for access
- New blank page with header (auth = bulk)
---
- [Frontend](https://nr-gwells-177-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-177-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat(frontend): #173 Blank Page Setup for X-Tool

.github/workflows/merge.yml
---
- [Frontend](https://nr-gwells-216-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-216-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Update merge workflow to deploy to prod.

frontend/src/common/mapbox/layers.js, frontend/src/common/mapbox/popup.js, frontend/src/wells/components/SearchMap.vue, frontend/src/wells/components/SingleWellMap.vue, frontend/src/wells/popup.js, frontend/src/wells/views/WellDetail.vue
The well layer, with the popups, has been added to the Well Detail page. Popups show up for everything but the selected well.
Fixes # 207
---
- [Frontend](https://nr-gwells-215-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-215-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat(frontend): add well layer to Well Detail map

.github/workflows/merge.yml, backend/openshift.deploy.yml, docker-compose.yml, frontend/openshift.deploy.yml
---
- [Frontend](https://nr-gwells-221-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-221-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore(ci): Update route naming.

.github/workflows/analysis.yml
---
- [Frontend](https://nr-gwells-226-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-226-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: catch canceled jobs

.github/workflows/analysis.yml
---
- [Frontend](https://nr-gwells-227-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-227-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci(fix): catch canceled jobs

.github/workflows/.tests.yml, .github/workflows/analysis.yml
---
- [Frontend](https://nr-gwells-240-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-gwells-240-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): remove JS handling from workflow conditionals
